version: 0.2

env:
  variables:
    parameter-store:
    DOCKER_REGISTERY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTERY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTERY_URL: /myapp/docker-registery/url
phases: 
  install:
#If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions
#If you specify runtime-versions and use an image other than Ubuntu standard image 2.
   runtime-versions:
     python: 3.11
  pre_build:
    commands :
    - pip install -r simple-python-app/requirements.txt
  build:
    commands :
     - cd simple-python-app
     - echo "Building Docker Image"
     - echo "Salar@5000" | docker login -u "ajay4720" --password-stdin "docker.io"
     - docker build -t "docker.io/ajay4720/simple-python-flask-app:latest" .
     - docker push "docker.io/ajay4720/simple-python-flask-app:latest"
  post_build:
    commands:
     - echo "Build is Successful"
artifacts:
  files:
    - '**/*'
   name: dev1-artifact  
  base-directory: ../simple-python-app
  discard-paths: no

